name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Replace version in style.css 
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "Version: [0-9\\.]{1,}"
          replace: "Version: ${{ steps.tag_version.outputs.new_tag }}"
          regex: false
      - name: Replace version in functions.php
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "define\\('MIKKELI_VERSION', '[0-9\\.]{1,}'\\);"
          replace: "define\\('MIKKELI_VERSION', '${{ steps.tag_version.outputs.new_tag }}');"
          regex: false
